const INCREASE_AMOUNT = 'INCREASE_AMOUNT'
const DECREASE_AMOUNT = 'DECREASE_AMOUNT'
const CLEAR_CART = 'CLEAR_CART'
const REMOVE_ITEM = 'REMOVE_ITEM'
const GET_TOTALS = 'GET_TOTALS'
const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT'
const DIRECT_CHECKOUT = 'DIRECT_CHECKOUT'
const ADD_TO_CART = 'ADD_TO_CART'

export {
    INCREASE_AMOUNT,
    DECREASE_AMOUNT,
    CLEAR_CART,
    REMOVE_ITEM,
    TOGGLE_AMOUNT,
    GET_TOTALS,
    DIRECT_CHECKOUT,
    ADD_TO_CART,
}
